### ISSUE TITLE
Instagram gallery downloader not working

### ISSUE THREAD

**Issue by aurosalinda** [CuddleBear92/Hydrus-Presets-and-Scripts#125]
When I try to download a gallery it says that doesn't find any files. Maybe something changed in the API?

**Comment by Nifle-CGE** [comment]
Idk if it's just me but when I use the new downloader I still get an error:
```ParseException("Page Parser instagram user gallery api parser: Content Parser first page next gallery page url: Unable to parse that JSON: JSONDecodeError('Expecting value: line 1 column 1 (char 0)'). Parsing text sample: ")… (Copy note to see full error)
Traceback (most recent call last):
  File "hydrus/client/ClientParsing.py", line 1905, in _ParseRawTexts
  File "hydrus/client/caches/ClientCaches.py", line 80, in GetJSON
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hydrus/client/ClientParsing.py", line 2316, in Parse
  File "hydrus/client/ClientParsing.py", line 783, in Parse
  File "hydrus/client/ClientParsing.py", line 902, in _ParseRawTexts
  File "hydrus/client/ClientParsing.py", line 783, in Parse
  File "hydrus/client/ClientParsing.py", line 1920, in _ParseRawTexts
hydrus.core.HydrusExceptions.ParseException: Unable to parse that JSON: JSONDecodeError('Expecting value: line 1 column 1 (char 0)'). Parsing text sample: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hydrus/client/ClientParsing.py", line 2701, in Parse
  File "hydrus/client/ClientParsing.py", line 2324, in Parse
hydrus.core.HydrusExceptions.ParseException: Content Parser first page next gallery page url: Unable to parse that JSON: JSONDecodeError('Expecting value: line 1 column 1 (char 0)'). Parsing text sample: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hydrus/client/importing/ClientImportGallerySeeds.py", line 507, in WorkOnURL
  File "hydrus/client/ClientParsing.py", line 2715, in Parse
hydrus.core.HydrusExceptions.ParseException: Page Parser instagram user gallery api parser: Content Parser first page next gallery page url: Unable to parse that JSON: JSONDecodeError('Expecting value: line 1 column 1 (char 0)'). Parsing text sample: 
```
